### ISSUE TITLE
@perseidesjs/medusa-otp unable to add in npm 

### ISSUE THREAD

**Issue by prakashrandy18** [perseidesjs/medusa-plugin-otp#1]
Error starting server
Error: Unable to find plugin "@perseidesjs/medusa-otp". Perhaps you need to install its package?

i have tried installing by npm  i @perseidesjs/medusa-otp am getting below error 

> rak@Prakashs-MacBook-Air commerce % npm i @perseidesjs/medusa-otp
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @hookform/error-message@2.0.1
npm WARN Found: react-hook-form@7.38.0
npm WARN node_modules/@hookform/error-message/node_modules/react-hook-form
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-hook-form@"^7.0.0" from @hookform/error-message@2.0.1
npm WARN node_modules/@hookform/error-message
npm WARN   @hookform/error-message@"^2.0.1" from @medusajs/admin-ui@2.1.16
npm WARN   node_modules/@medusajs/admin-ui
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @rsc-labs/medusa-affiliate-discount@0.2.0
npm ERR! Found: @medusajs/medusa@1.20.8
npm ERR! node_modules/@medusajs/medusa
npm ERR!   peer @medusajs/medusa@"^1.12.0" from medusa-file-spaces@1.4.1
npm ERR!   node_modules/medusa-file-spaces
npm ERR!     medusa-file-spaces@"^1.4.1" from the root project
npm ERR!   peer @medusajs/medusa@"^1.12.0" from medusa-file-s3@1.4.2
npm ERR!   node_modules/medusa-file-s3
npm ERR!     medusa-file-s3@"^1.4.2" from the root project
npm ERR!   17 more (medusa-payment-stripe, medusa-test-utils, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @medusajs/medusa@"1.19.0" from @rsc-labs/medusa-affiliate-discount@0.2.0
npm ERR! node_modules/@rsc-labs/medusa-affiliate-discount
npm ERR!   @rsc-labs/medusa-affiliate-discount@"^0.2.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @medusajs/medusa@1.19.0
npm ERR! node_modules/@medusajs/medusa
npm ERR!   peer @medusajs/medusa@"1.19.0" from @rsc-labs/medusa-affiliate-discount@0.2.0
npm ERR!   node_modules/@rsc-labs/medusa-affiliate-discount
npm ERR!     @rsc-labs/medusa-affiliate-discount@"^0.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/prak/.npm/_logs/2024-08-21T11_24_34_531Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/prak/.npm/_logs/2024-08-21T11_24_34_531Z-debug-0.log

**Comment by adevinwild** [comment]
Hi @prakashrandy18 !
Sorry for the late answer, it's because it should be `@perseidesjs/medusa-plugin-otp` and not `@perseidesjs/medusa-otp` 🙌

I've updated the typo on the docs just right now

**Comment by prakashrandy18** [comment]
Yes, You're right..Thank you @adevinwild for the response.
